packages:
  - ./packages/*
  - ./apps/web/**
  - ./apps/docs/**
  - ./apps/video
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - sqlite3
nodeLinker: hoisted