// Generated by cursor sonnet 4

"use client";

import { format, isValid, parse } from "date-fns";
import { zhTW } from "date-fns/locale";
import { CalendarIcon } from "lucide-react";
import * as React from "react";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Input } from "@/components/ui/input";
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";

interface DatePickerProps {
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
    className?: string;
}

export function DatePicker({
    value,
    onChange,
    placeholder,
    className,
}: DatePickerProps) {
    const [isOpen, setIsOpen] = React.useState(false);
    const [inputValue, setInputValue] = React.useState(value);

    // 解析 DICOM 日期格式 (YYYYMMDD)
    const parseDate = (dateStr: string): Date | null => {
        if (!dateStr || dateStr.length !== 8) return null;

        const parsed = parse(dateStr, "yyyyMMdd", new Date());
        return isValid(parsed) ? parsed : null;
    };

    // 格式化為 DICOM 日期格式
    const formatDate = (date: Date): string => {
        return format(date, "yyyyMMdd");
    };

    const selectedDate = parseDate(value);

    const handleDateSelect = (date: Date | undefined) => {
        if (date) {
            const formatted = formatDate(date);
            setInputValue(formatted);
            onChange(formatted);
            setIsOpen(false);
        }
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const newValue = e.target.value;
        setInputValue(newValue);

        // 驗證並更新 如果是有效的8位數字
        if (/^\d{8}$/.test(newValue)) {
            const parsed = parseDate(newValue);
            if (parsed) {
                onChange(newValue);
            }
        } else if (newValue === "") {
            onChange("");
        }
    };

    const handleInputBlur = () => {
        // 如果輸入無效，回復到上一個有效值
        if (inputValue !== value && !parseDate(inputValue)) {
            setInputValue(value);
        }
    };

    return (
        <div className={cn("flex items-center space-x-2", className)}>
            <Input
                value={inputValue}
                onChange={handleInputChange}
                onBlur={handleInputBlur}
                placeholder={placeholder || "YYYYMMDD"}
                className="w-32"
                maxLength={8}
            />

            <Popover open={isOpen} onOpenChange={setIsOpen}>
                <PopoverTrigger asChild>
                    <Button variant="outline" size="sm" className="px-3">
                        <CalendarIcon className="h-4 w-4" />
                    </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                    <Calendar
                        mode="single"
                        selected={selectedDate || undefined}
                        onSelect={handleDateSelect}
                        locale={zhTW}
                        autoFocus
                    />
                </PopoverContent>
            </Popover>
        </div>
    );
}
