// Generated by cursor sonnet 4

"use client";

import * as React from "react";
import { useT } from "@/app/_i18n/client";
import { DatePicker } from "@/components/ui/date-picker";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";

type DateRangeType = "exact" | "from" | "to" | "range";

interface DateRangePickerProps {
    value: string;
    onChange: (value: string) => void;
    className?: string;
}

export function DateRangePicker({
    value,
    onChange,
    className,
}: DateRangePickerProps) {
    const { t } = useT("translation");
    // 解析當前值來決定類型和日期
    const parseValue = (
        val: string,
    ): { type: DateRangeType; fromDate: string; toDate: string } => {
        if (!val) return { type: "exact", fromDate: "", toDate: "" };

        if (/^(\d{8})\s*-\s*(\d{8})$/.test(val)) {
            const [, from, to] = val.match(/^(\d{8})\s*-\s*(\d{8})$/) || [];
            return { type: "range", fromDate: from, toDate: to };
        } else if (/^-\s*(\d{8})$/.test(val)) {
            const [, to] = val.match(/^-\s*(\d{8})$/) || [];
            return { type: "to", fromDate: "", toDate: to };
        } else if (/^(\d{8})\s*-$/.test(val)) {
            const [, from] = val.match(/^(\d{8})\s*-$/) || [];
            return { type: "from", fromDate: from, toDate: "" };
        } else if (/^\d{8}$/.test(val)) {
            return { type: "exact", fromDate: val, toDate: "" };
        }

        return { type: "exact", fromDate: "", toDate: "" };
    };

    const { type, fromDate, toDate } = parseValue(value);
    const [rangeType, setRangeType] = React.useState<DateRangeType>(type);
    const [fromValue, setFromValue] = React.useState(fromDate);
    const [toValue, setToValue] = React.useState(toDate);

    // 更新最終值
    const updateValue = React.useCallback(
        (newType: DateRangeType, newFrom: string, newTo: string) => {
            let result = "";

            switch (newType) {
                case "exact":
                    result = newFrom;
                    break;
                case "from":
                    result = newFrom ? `${newFrom}-` : "";
                    break;
                case "to":
                    result = newTo ? `-${newTo}` : "";
                    break;
                case "range":
                    result = newFrom && newTo ? `${newFrom}-${newTo}` : "";
                    break;
            }

            onChange(result);
        },
        [onChange],
    );

    const handleTypeChange = (newType: DateRangeType) => {
        setRangeType(newType);
        updateValue(newType, fromValue, toValue);
    };

    const handleFromChange = (newFrom: string) => {
        setFromValue(newFrom);
        updateValue(rangeType, newFrom, toValue);
    };

    const handleToChange = (newTo: string) => {
        setToValue(newTo);
        updateValue(rangeType, fromValue, newTo);
    };

    return (
        <div className={cn("space-y-2", className)}>
            <Select value={rangeType} onValueChange={handleTypeChange}>
                <SelectTrigger className="w-40">
                    <SelectValue />
                </SelectTrigger>
                <SelectContent>
                    <SelectItem value="exact">{t("dicom.search.dateRangePicker.exact")}</SelectItem>
                    <SelectItem value="from">{t("dicom.search.dateRangePicker.from")}</SelectItem>
                    <SelectItem value="to">{t("dicom.search.dateRangePicker.to")}</SelectItem>
                    <SelectItem value="range">{t("dicom.search.dateRangePicker.range")}</SelectItem>
                </SelectContent>
            </Select>

            <div className="flex items-center space-x-2">
                {(rangeType === "exact" ||
                    rangeType === "from" ||
                    rangeType === "range") && (
                    <DatePicker
                        value={fromValue}
                        onChange={handleFromChange}
                        placeholder={t("dicom.search.dateRangePicker.startDate")}
                    />
                )}

                {rangeType === "range" && (
                    <span className="text-muted-foreground">至</span>
                )}

                {(rangeType === "to" || rangeType === "range") && (
                    <DatePicker
                        value={toValue}
                        onChange={handleToChange}
                        placeholder={t("dicom.search.dateRangePicker.endDate")}
                    />
                )}
            </div>
        </div>
    );
}
