import { DICOM_TAG_KEYWORD_REGISTRY } from "./dicomTagKeywordRegistry";

/**
 * FROM [Table C.7-1. Patient Module Attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.html#table_C.7-1)
 */
export const PATIENT_TAGS_TO_STORE = [
    DICOM_TAG_KEYWORD_REGISTRY.PatientName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.IssuerOfPatientID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBirthDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBirthDateInAlternativeCalendar.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientDeathDateInAlternativeCalendar.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientAlternativeCalendar.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSex.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReferencedPatientPhotoSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBirthTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.OtherPatientIDsSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.OtherPatientNames.tag,
    DICOM_TAG_KEYWORD_REGISTRY.EthnicGroupCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.EthnicGroup.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientComments.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSpeciesDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSpeciesCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBreedDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBreedCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.BreedRegistrationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StrainDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StrainNomenclature.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StrainCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StrainAdditionalInformation.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StrainStockSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.GeneticModificationsSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ResponsiblePerson.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ResponsiblePersonRole.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ResponsibleOrganization.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientIdentityRemoved.tag,
    DICOM_TAG_KEYWORD_REGISTRY.DeidentificationMethod.tag,
    DICOM_TAG_KEYWORD_REGISTRY.DeidentificationMethodCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StorageMediaFileSetID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StorageMediaFileSetUID.tag,
] as const;


/**
 * tag from: {@link https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.2.html|Common Study IE Modules}
 * and {@link https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.2.2.html|Patient Study Module}
 */
export const STUDY_TAGS_TO_STORE = [
    DICOM_TAG_KEYWORD_REGISTRY.SpecificCharacterSet.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StudyInstanceUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StudyDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StudyTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReferringPhysicianName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReferringPhysicianIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ConsultingPhysicianName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ConsultingPhysicianIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StudyID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AccessionNumber.tag,
    DICOM_TAG_KEYWORD_REGISTRY.IssuerOfAccessionNumberSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.StudyDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PhysiciansOfRecord.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PhysiciansOfRecordIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.NameOfPhysiciansReadingStudy.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PhysiciansReadingStudyIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RequestingService.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RequestingServiceCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReferencedStudySequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ProcedureCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReasonForPerformedProcedureCodeSequence.tag,
    // Patient Study Module Attributes
    DICOM_TAG_KEYWORD_REGISTRY.AdmittingDiagnosesDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AdmittingDiagnosesCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PrimaryDiagnosisCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SecondaryDiagnosesCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.HistologicalDiagnosesCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientAge.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSize.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientWeight.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientBodyMassIndex.tag,
    DICOM_TAG_KEYWORD_REGISTRY.MeasuredAPDimension.tag,
    DICOM_TAG_KEYWORD_REGISTRY.MeasuredLateralDimension.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSizeCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.MedicalAlerts.tag,
    DICOM_TAG_KEYWORD_REGISTRY.Allergies.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SmokingStatus.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PregnancyStatus.tag,
    DICOM_TAG_KEYWORD_REGISTRY.LastMenstrualDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientState.tag,
    DICOM_TAG_KEYWORD_REGISTRY.Occupation.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AdditionalPatientHistory.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AdmissionID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.IssuerOfAdmissionIDSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReasonForVisit.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReasonForVisitCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ServiceEpisodeID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.IssuerOfServiceEpisodeIDSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ServiceEpisodeDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientSexNeutered.tag,
    DICOM_TAG_KEYWORD_REGISTRY.GenderIdentitySequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SexParametersForClinicalUseCategorySequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PersonNamesToUseSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ThirdPersonPronounsSequence.tag
] as const;

/**
 * [General Series Module Attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_c.7.3.html)
 */
export const SERIES_TAGS_TO_STORE = [
    DICOM_TAG_KEYWORD_REGISTRY.Modality.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesInstanceUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesNumber.tag,
    DICOM_TAG_KEYWORD_REGISTRY.Laterality.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PerformingPhysicianName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PerformingPhysicianIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ProtocolName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesDescription.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SeriesDescriptionCodeSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.OperatorsName.tag,
    DICOM_TAG_KEYWORD_REGISTRY.OperatorIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ReferencedPerformedProcedureStepSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RelatedSeriesSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.BodyPartExamined.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientPosition.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SmallestPixelValueInSeries.tag,
    DICOM_TAG_KEYWORD_REGISTRY.LargestPixelValueInSeries.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RequestAttributesSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AnatomicalOrientationType.tag,
    DICOM_TAG_KEYWORD_REGISTRY.TreatmentSessionUID.tag
];

/**
 * [General Image Module Attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.html)
 * and [SOP Common Module Attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.12.html#sect_C.12.1)
 */
export const INSTANCE_TAGS_TO_STORE = [
    // SOP Common Module Attributes
    DICOM_TAG_KEYWORD_REGISTRY.SOPClassUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SOPInstanceUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SpecificCharacterSet.tag,
    DICOM_TAG_KEYWORD_REGISTRY.InstanceCreationDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.InstanceCreationTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.InstanceCoercionDateTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.InstanceCreatorUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RelatedGeneralSOPClassUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.OriginalSpecializedSOPClassUID.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SyntheticData.tag,
    DICOM_TAG_KEYWORD_REGISTRY.CodingSchemeIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ContextGroupIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.MappingResourceIdentificationSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.TimezoneOffsetFromUTC.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ContributingEquipmentSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SOPInstanceStatus.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SOPAuthorizationDateTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.SOPAuthorizationComment.tag,
    DICOM_TAG_KEYWORD_REGISTRY.AuthorizationEquipmentCertificationNumber.tag,
    DICOM_TAG_KEYWORD_REGISTRY.EncryptedAttributesSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.HL7StructuredDocumentReferenceSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.LongitudinalTemporalInformationModified.tag,
    DICOM_TAG_KEYWORD_REGISTRY.QueryRetrieveView.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ConversionSourceAttributesSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ContentQualification.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PrivateDataElementCharacteristicsSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.InstanceOriginStatus.tag,
    DICOM_TAG_KEYWORD_REGISTRY.BarcodeValue.tag,
    // General Image Module Attributes
    DICOM_TAG_KEYWORD_REGISTRY.InstanceNumber.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PatientOrientation.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ContentDate.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ContentTime.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ImageType.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ImageComments.tag,
    DICOM_TAG_KEYWORD_REGISTRY.QualityControlImage.tag,
    DICOM_TAG_KEYWORD_REGISTRY.BurnedInAnnotation.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RecognizableVisualFeatures.tag,
    DICOM_TAG_KEYWORD_REGISTRY.LossyImageCompression.tag,
    DICOM_TAG_KEYWORD_REGISTRY.LossyImageCompressionRatio.tag,
    DICOM_TAG_KEYWORD_REGISTRY.IconImageSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.PresentationLUTShape.tag,
    DICOM_TAG_KEYWORD_REGISTRY.RealWorldValueMappingSequence.tag,
    DICOM_TAG_KEYWORD_REGISTRY.ImageLaterality.tag
];