export const WORKSPACE_PERMISSIONS = {
    READ: 1 << 0,
    CREATE: 1 << 1,
    UPDATE: 1 << 2,
    DELETE: 1 << 3,
    INVITE: 1 << 4,
    MANAGE: 1 << 5,
    FULL: (1 << 6) - 1,
} as const;

export const WORKSPACE_PERMISSION_NAMES = {
    [WORKSPACE_PERMISSIONS.READ]: "READ",
    [WORKSPACE_PERMISSIONS.CREATE]: "CREATE",
    [WORKSPACE_PERMISSIONS.UPDATE]: "UPDATE",
    [WORKSPACE_PERMISSIONS.DELETE]: "DELETE",
    [WORKSPACE_PERMISSIONS.INVITE]: "INVITE",
    [WORKSPACE_PERMISSIONS.MANAGE]: "MANAGE",
} as const;

export type WorkspacePermissionsType = typeof WORKSPACE_PERMISSIONS[keyof typeof WORKSPACE_PERMISSIONS];

export const ROLE_PERMISSION_TEMPLATES = {
    viewer: WORKSPACE_PERMISSIONS.READ,
    editor: WORKSPACE_PERMISSIONS.READ | WORKSPACE_PERMISSIONS.CREATE | WORKSPACE_PERMISSIONS.UPDATE,
    maintainer: WORKSPACE_PERMISSIONS.READ | WORKSPACE_PERMISSIONS.CREATE | WORKSPACE_PERMISSIONS.UPDATE | WORKSPACE_PERMISSIONS.DELETE,
    admin: WORKSPACE_PERMISSIONS.READ | WORKSPACE_PERMISSIONS.CREATE | WORKSPACE_PERMISSIONS.UPDATE | WORKSPACE_PERMISSIONS.DELETE | WORKSPACE_PERMISSIONS.INVITE,
    owner: WORKSPACE_PERMISSIONS.FULL,
} as const;
